# Generated by Django 4.1.3 on 2022-12-07 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0006_alter_perfil_nick_name'),
        ('Grupo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='administrador',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='foto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='Grupo_app.grupo'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='ingressou_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='Perfil_app.perfil'),
        ),
    ]
