# Generated by Django 4.1.3 on 2022-12-07 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0006_alter_perfil_nick_name'),
        ('Grupo_app', '0002_participante_administrador_alter_grupo_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='Perfil_app.perfil'),
        ),
    ]
