# Generated by Django 4.1.3 on 2022-12-07 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grupo_app', '0003_alter_participante_participante'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(blank=True, max_length=255, null=True)),
                ('de', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='Grupo_app.participante')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='Grupo_app.grupo')),
            ],
            options={
                'verbose_name': 'MensagemGrupo',
                'verbose_name_plural': 'MensagemGrupos',
            },
        ),
    ]
