# Generated by Django 4.1.3 on 2022-12-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=128, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('sexo', models.CharField(blank=True, max_length=16, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
