# Generated by Django 4.1.3 on 2022-11-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='data_inserido',
            new_name='data_cadastro',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='nome',
            new_name='nome_completo',
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nick_name',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
