# Generated by Django 4.1.3 on 2023-01-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_amizade', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='amigos',
            field=models.ManyToManyField(blank=True, related_name='amigos_rel', to='Perfil_app.perfil'),
        ),
    ]
