# Generated by Django 4.1.3 on 2022-12-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0004_alter_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nick_name',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
