# Generated by Django 4.1.3 on 2023-01-15 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0002_initial'),
        ('Amigo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoamizade',
            name='status',
            field=models.CharField(choices=[('pendente', 'pendente'), ('aceito', 'aceito'), ('rejeitado', 'rejeitado')], max_length=16),
        ),
        migrations.CreateModel(
            name='Amigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_amizade', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amigos_usuario1', to='Perfil_app.perfil')),
                ('usuario2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amigos_usuario2', to='Perfil_app.perfil')),
            ],
        ),
    ]
