# Generated by Django 4.1.3 on 2022-12-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amigo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoamizade',
            name='mensagem',
            field=models.CharField(default='Olá, quero ser seu amigo!', max_length=128, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='solicitacaoamizade',
            name='status',
            field=models.CharField(choices=[('pendente', 'pendente'), ('aceito', 'aceito'), ('rejeitado', 'rejeitado')], max_length=255),
        ),
    ]
