# Generated by Django 4.1.3 on 2023-01-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amigo_app', '0002_alter_solicitacaoamizade_status_amigos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amigos',
        ),
    ]
