# Generated by Django 4.1.3 on 2022-12-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ccampo_teste',
        ),
        migrations.AddField(
            model_name='user',
            name='primeiro_nome',
            field=models.CharField(max_length=32, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='user',
            name='sobrenome',
            field=models.CharField(max_length=128, null=True, verbose_name=''),
        ),
    ]
