# Generated by Django 4.1.3 on 2022-12-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mensagem_app', '0001_initial'),
        ('Perfil_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfil_app.perfil'),
        ),
        migrations.AddField(
            model_name='chat',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Perfil_app.perfil'),
        ),
    ]
