# Generated by Django 4.1.3 on 2022-11-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
