# Generated by Django 4.1.3 on 2022-12-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postagem_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postagem',
            old_name='album',
            new_name='fotos',
        ),
        migrations.AddField(
            model_name='postagem',
            name='texto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
