# Generated by Django 4.1.3 on 2023-01-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postagem_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='data_postagem',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da postagem'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto qualquer da postagem'),
        ),
    ]
