# Generated by Django 4.1.3 on 2023-01-15 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0003_amigos_perfil_amigos'),
        ('Album_app', '0002_initial'),
        ('Postagem_app', '0002_postagem_data_postagem_alter_postagem_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='fotos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='Album_app.album'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minhas_postagens', to='Perfil_app.perfil'),
        ),
    ]
