# Generated by Django 4.1.3 on 2023-01-16 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Postagem_app', '0003_alter_postagem_fotos_alter_postagem_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='dislike',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dislike'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Like'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario feito na postagem, atualmente sem limite de caracteres')),
                ('postagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Postagem_app.postagem')),
            ],
            options={
                'verbose_name': 'Comentario Postagem',
                'verbose_name_plural': 'Comentarios em Postagens',
            },
        ),
    ]
